name: Github Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -IU -r requirements.txt
    - run: |
        git remote add gh-token "https://${GH_TOKEN}@github.com/giansalex/peru-consult.git";
        git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
        mkdocsVersion=$(pip show mkdocs | grep Version);
        mkdocs gh-deploy -v --clean --remote-name gh-token --message "Deployed MkDocs $mkdocsVersion";
 
      env:
        GH_TOKEN: ${{ secrets.ghToken }}
